# Generated by Django 6.1 on 2026-08-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=120, verbose_name='judul')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Urutan tampil, dari pintu masuk paling luas ke paling khusus.', verbose_name='urutan')),
            ],
            options={
                'verbose_name': 'koleksi',
                'verbose_name_plural': 'koleksi',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nama')),
            ],
            options={
                'verbose_name': 'bentuk video',
                'verbose_name_plural': 'bentuk video',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='judul')),
                ('artist', models.CharField(max_length=200, verbose_name='artis')),
                ('youtube_id', models.CharField(help_text='Satu URL YouTube harus menjadi satu entri.', max_length=20, unique=True, verbose_name='ID YouTube')),
                ('region', models.CharField(help_text='Kabupaten atau kota.', max_length=120, verbose_name='daerah')),
                ('customary_region', models.CharField(choices=[('Mamta', 'Mamta'), ('Saireri', 'Saireri'), ('Domberai', 'Domberai'), ('Bomberai', 'Bomberai'), ('Ha Anim', 'Ha Anim'), ('La Pago', 'La Pago'), ('Mee Pago', 'Mee Pago'), ('Lintas wilayah adat', 'Lintas wilayah adat'), ('Belum dipastikan', 'Belum dipastikan')], default='Belum dipastikan', max_length=40, verbose_name='wilayah adat')),
                ('language', models.CharField(max_length=120, verbose_name='bahasa')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='tahun')),
                ('duration', models.CharField(blank=True, max_length=12, verbose_name='durasi')),
                ('note', models.CharField(help_text='Satu kalimat; dipakai sebagai meta description.', max_length=300, verbose_name='catatan singkat')),
                ('description', models.TextField(verbose_name='deskripsi')),
                ('context', models.TextField(help_text='Asal sumbernya, dan apa yang masih belum pasti.', verbose_name='konteks')),
                ('is_featured', models.BooleanField(default=False, help_text='Tampil di baris pilihan editor pada halaman Jelajah.', verbose_name='pilihan editor')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Urutan tampil di dalam kategorinya.', verbose_name='urutan')),
                ('is_published', models.BooleanField(default=True, help_text='Draft hasil usulan mulai dari tidak tercentang.', verbose_name='terbit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui')),
                ('collection', models.ForeignKey(help_text='Tepat satu kategori Jelajah.', on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='catalog.collection', verbose_name='koleksi')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VideoFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Yang pertama tampil sebagai label di kartu video.', verbose_name='urutan')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='catalog.format', verbose_name='bentuk video')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_formats', to='catalog.video', verbose_name='video')),
            ],
            options={
                'verbose_name': 'bentuk video pada video',
                'verbose_name_plural': 'bentuk video pada video',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='formats',
            field=models.ManyToManyField(related_name='videos', through='catalog.VideoFormat', to='catalog.format', verbose_name='bentuk video'),
        ),
        migrations.AddConstraint(
            model_name='videoformat',
            constraint=models.UniqueConstraint(fields=('video', 'format'), name='unique_video_format'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_published'], name='catalog_vid_is_publ_33f0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['position', 'title'], name='catalog_vid_positio_9928cb_idx'),
        ),
    ]
