# Generated by Django 6.1 on 2026-08-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Tampil di baris pilihan kurator pada halaman Jelajah.', verbose_name='pilihan kurator'),
        ),
    ]
