# Generated by Django 6.1 on 2026-08-23 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(max_length=300)),
                ('youtube_id', models.CharField(blank=True, help_text='Diambil dari tautan saat disimpan; dipakai untuk mendeteksi duplikat.', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('performer', models.CharField(help_text='Artis, grup, atau koor.', max_length=200)),
                ('description', models.TextField(help_text='Konteks, asal, atau makna lagu yang diketahui.')),
                ('status', models.CharField(choices=[('NEW', 'Baru'), ('IN_REVIEW', 'Sedang ditinjau'), ('ACCEPTED', 'Diterima'), ('REJECTED', 'Ditolak')], default='NEW', max_length=12)),
                ('curator_note', models.TextField(blank=True, help_text='Alasan penolakan, atau catatan tinjauan. Wajib saat menolak.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_from', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usulan',
                'verbose_name_plural': 'usulan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='submissions_status_fa968c_idx')],
            },
        ),
    ]
