# Generated by Django 6.1 on 2026-08-23 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='dibuat'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='curator_note',
            field=models.TextField(blank=True, help_text='Alasan penolakan, atau catatan tinjauan. Wajib saat menolak.', verbose_name='catatan kurator'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(help_text='Konteks, asal, atau makna lagu yang diketahui.', verbose_name='deskripsi'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='performer',
            field=models.CharField(help_text='Artis, grup, atau koor.', max_length=200, verbose_name='artis atau pelaku'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='waktu tinjauan'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='ditinjau oleh'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('NEW', 'Baru'), ('IN_REVIEW', 'Sedang ditinjau'), ('ACCEPTED', 'Diterima'), ('REJECTED', 'Ditolak')], default='NEW', max_length=12, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_from',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='dikirim dari'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=200, verbose_name='judul'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='diperbarui'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Diambil dari tautan saat disimpan; dipakai untuk mendeteksi duplikat.', max_length=20, verbose_name='ID YouTube'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='youtube_url',
            field=models.URLField(max_length=300, verbose_name='tautan YouTube'),
        ),
    ]
